[cursor]
style = "Beam"

[font]
size = 10.0

#[font.normal]
#family = "RobotoMono Nerd Font"

[window]
opacity = 0.9

[window.padding]
x = 8
y = 8

[colors.normal]
#black = "#21222c"
black = "#6fff65"
red = "#ff5555"
green = "#50fa7b"
yellow = "#ecf436"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#0d001a"
#foreground = "#d8beff"
foreground = "#6fff65"
# foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
